name: Feature workflow

on:
  push:
    branches:
      - feature/**
      - bugfix/**

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build and publish with Maven
      run: |
        VERSION=$(./build/create-semver.sh spring-core/pom.xml "${{github.run_number}}-$GITHUB_SHA")
        echo "ARTIFACT_VERSION=${VERSION}" >> $GITHUB_ENV
        mvn -B versions:set -DnewVersion="${VERSION}" --file spring-core/pom.xml
        mvn -B deploy --file spring-core/pom.xml
        cp "spring-core/target/core-${VERSION}.jar" "spring-core/target/spring-core.jar"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
          docker build ./spring-core -t ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/spring-core:${{ env.ARTIFACT_VERSION }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/spring-core:${{ env.ARTIFACT_VERSION }}
